name: deploy
#on:
#  pull_request:
#    branches:
#      - main
# 推送 main 分支触发构建
on:
  push:
    branches: [ main ]
env:
  SOURCE_DIR: README.md
  TARGET_DIR: /home/tnuser
  GO_VERSION: 1.18
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up Go version  ${{ env.GO_VERSION }}
        uses: actions/setup-go@v2
        with:
          go-version:  ${{ env.GO_VERSION }}
      - run: go version
      - run: go env -w GO111MODULE=on
      - run: go mod tidy
      - run: make install

      - name: Deploy to Server
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.SERVER_HOST }}
          user: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          connect_timeout: 180s
          scp: |
            ${{ env.SOURCE_DIR }} => ${{ env.TARGET_DIR }}
          last_ssh: |
            sh /home/tnuser/deploy-all.sh