name: deploy
on:
  push:
    branches: [ main ]
env:
  DEPLOY_DIR: /home/ubuntu/
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Deploy to Server
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.SERVER_HOST }}
          user: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          connect_timeout: 180s
          scp: |
            README.md => ${{ env.DEPLOY_DIR }}
          last_ssh: |
            ll
